import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookmarkPlus, Copy, Pencil, Plus, Search, Trash2, X, BookOpenText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";
import { staffRequest } from "@/lib/staff-api";
import { copyText } from "@/lib/copy-text";
import type { AIKnowledge, SavedResponse } from "@shared/assistant-schema";

type Item = SavedResponse | AIKnowledge;
const categories = ["Initial outreach","Follow-up","Pricing","10% Plan","20% Management","Onboarding","Calendar synchronization","Platform questions","Owner objections","No response follow-up","Trust/company information","Spanish","English","General"];

export default function StaffLibraryPage({ knowledge = false }: { knowledge?: boolean }) {
  const resource = knowledge ? "knowledge" : "saved-responses";
  const endpoint = `/api/assistant/${resource}`;
  const qc=useQueryClient(); const {toast}=useToast();
  const [search,setSearch]=useState(""); const [formOpen,setFormOpen]=useState(false); const [editing,setEditing]=useState<string|null>(null);
  const [title,setTitle]=useState(""); const [category,setCategory]=useState(""); const [content,setContent]=useState("");
  const query=useQuery<Item[]>({queryKey:[endpoint],queryFn:()=>staffRequest("GET",endpoint),retry:false});
  const describeError=(error:unknown)=>error instanceof Error?error.message.replace(/^\d+:/,""):"Please try again.";
  const save=useMutation({mutationFn:()=>staffRequest("POST",endpoint,{title:title.trim(),category:category.trim(),content:content.trim()}),onSuccess:()=>{qc.invalidateQueries({queryKey:[endpoint]});closeForm();toast({title:knowledge?"Knowledge item added":"Response saved"});},onError:error=>toast({title:knowledge?"Knowledge could not be added":"Response could not be saved",description:describeError(error),variant:"destructive"})});
  const update=useMutation({mutationFn:()=>staffRequest("PATCH",`${endpoint}/${editing}`,{title:title.trim(),category:category.trim(),content:content.trim()}),onSuccess:()=>{qc.invalidateQueries({queryKey:[endpoint]});closeForm();toast({title:"Changes saved"});},onError:error=>toast({title:"Changes could not be saved",description:describeError(error),variant:"destructive"})});
  const remove=useMutation({mutationFn:(id:string)=>staffRequest("DELETE",`${endpoint}/${id}`),onSuccess:()=>{qc.invalidateQueries({queryKey:[endpoint]});toast({title:knowledge?"Knowledge item deleted":"Response deleted"});},onError:error=>toast({title:knowledge?"Knowledge item could not be deleted":"Response could not be deleted",description:describeError(error),variant:"destructive"})});
  const copy=async(value:string)=>{try{await copyText(value);toast({title:"Copied",description:"Text copied to clipboard."});}catch(error){toast({title:"Could not copy text",description:describeError(error),variant:"destructive"});}};
  function closeForm(){setFormOpen(false);setEditing(null);setTitle("");setCategory("");setContent("");}
  function startEdit(item:Item){setEditing(item.id);setTitle(item.title);setCategory(item.category);setContent(item.content);setFormOpen(true);}
  const filtered=(query.data||[]).filter(item=>`${item.title} ${item.category} ${item.content}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="mx-auto max-w-5xl space-y-6">
    <header className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-primary"><BookOpenText className="h-4 w-4"/><span className="text-xs font-semibold uppercase tracking-[.16em]">{knowledge?"Admin settings":"Personal staff library"}</span></div><h1 className="font-serif text-3xl font-semibold">{knowledge?"AI knowledge":"Saved responses"}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{knowledge?"Maintain global, approved information available to the assistant. Keep policy details current and verified.":"Save and reuse approved replies in your own staff library."}</p></div><Button className="h-11" onClick={()=>{closeForm();setFormOpen(true);}}><Plus className="mr-2 h-4 w-4"/>Add {knowledge?"knowledge":"response"}</Button></header>
    {knowledge&&<div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm leading-6"><strong>Global admin-managed source of truth.</strong> Changes here update knowledge shared across the assistant. Business rules are controlled by the server, not this interface.</div>}
    {formOpen&&<Card className="border-primary/30"><CardContent className="space-y-4 p-4 sm:p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-xl font-semibold">{editing?"Edit":"Add"} {knowledge?"knowledge item":"saved response"}</h2><Button variant="ghost" size="icon" onClick={closeForm} aria-label="Close form"><X className="h-4 w-4"/></Button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Title<Input className="mt-1.5" value={title} maxLength={120} onChange={e=>setTitle(e.target.value)} placeholder={knowledge?"e.g. Calendar synchronization":"e.g. First reply to property owner"}/></label><label className="text-sm font-medium">Category<Input className="mt-1.5" list="assistant-categories" value={category} maxLength={80} onChange={e=>setCategory(e.target.value)} placeholder="Choose or enter a category"/><datalist id="assistant-categories">{categories.map(c=><option key={c} value={c}/>)}</datalist></label></div><label className="block text-sm font-medium">Content<Textarea className="mt-1.5 min-h-40" maxLength={knowledge?20000:15000} value={content} onChange={e=>setContent(e.target.value)} placeholder={knowledge?"Write verified guidance for the assistant.":"Write the message exactly as staff should send it."}/></label><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="outline" onClick={closeForm}>Cancel</Button><Button disabled={!title.trim()||!category.trim()||!content.trim()||save.isPending||update.isPending} onClick={()=>editing?update.mutate():save.mutate()}>{editing?"Save changes":"Add to library"}</Button></div></CardContent></Card>}
    <div className="flex flex-col gap-3 sm:flex-row"><div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${knowledge?"knowledge":"responses"}…`} className="pl-9"/></div><p className="self-center text-xs text-muted-foreground">{filtered.length} {filtered.length===1?"item":"items"}</p></div>
    {query.isLoading?<div className="grid gap-3">{[1,2,3].map(n=><div key={n} className="h-28 animate-pulse rounded-xl border bg-muted/40"/>)}</div>:query.isError?<Card><CardContent className="p-8 text-center"><p className="font-medium">Could not load {knowledge?"AI knowledge":"saved responses"}.</p><p className="mt-1 text-sm text-muted-foreground">The server returned an error. Your saved work is unchanged.</p><Button variant="outline" className="mt-4" onClick={()=>query.refetch()}>Try again</Button></CardContent></Card>:filtered.length===0?<Card><CardContent className="px-6 py-12 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-muted text-muted-foreground"><BookmarkPlus className="h-5 w-5"/></div><h2 className="mt-4 font-serif text-xl font-semibold">{search?"No matches found":`No ${knowledge?"knowledge items":"saved responses"} yet`}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-muted-foreground">{search?"Try another search term.":knowledge?"Add approved guidance available to authorized staff across the assistant.":"Add a response to reuse it from your personal staff account."}</p>{!search&&<Button className="mt-5" onClick={()=>setFormOpen(true)}><Plus className="mr-2 h-4 w-4"/>Add first item</Button>}</CardContent></Card>:<div className="space-y-3">{filtered.map(item=><Card key={item.id} className="overflow-hidden"><CardContent className="flex min-w-0 flex-col gap-4 p-4 sm:flex-row sm:items-start sm:p-5"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold break-words">{item.title}</h2><Badge variant="secondary">{item.category}</Badge></div><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-6 text-muted-foreground">{item.content}</p><p className="mt-3 text-[11px] text-muted-foreground">Updated {new Date(item.updatedAt).toLocaleDateString()}</p></div><div className="flex shrink-0 gap-1 sm:flex-col"><Button variant="outline" size="sm" onClick={()=>copy(item.content)}><Copy className="mr-1.5 h-4 w-4"/>Copy</Button><Button variant="ghost" size="sm" onClick={()=>startEdit(item)}><Pencil className="mr-1.5 h-4 w-4"/>Edit</Button><Button variant="ghost" size="sm" className="text-destructive hover:text-destructive" onClick={()=>{if(window.confirm(`Delete “${item.title}”? This cannot be undone.`))remove.mutate(item.id);}}><Trash2 className="mr-1.5 h-4 w-4"/>Delete</Button></div></CardContent></Card>)}</div>}
  </div>;
}
