import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { ArrowUpRight, Mail, Phone, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { staffRequest } from "@/lib/staff-api";
import type { Lead } from "@shared/schema";

export default function StaffLeadsPage(){
 const q=useQuery<Lead[]>({queryKey:["/api/staff/leads"],queryFn:()=>staffRequest("GET","/api/staff/leads")});
 return <div className="mx-auto max-w-6xl space-y-6"><header className="border-b pb-5"><div className="mb-2 flex items-center gap-2 text-primary"><Users className="h-4 w-4"/><span className="text-xs font-semibold uppercase tracking-[.16em]">Staff workspace</span></div><h1 className="font-serif text-3xl font-semibold">Captured leads</h1><p className="mt-2 text-sm text-muted-foreground">Open a lead in IPM Assistant with their contact details prefilled.</p></header>
 {q.isLoading?<div className="space-y-3">{[1,2,3].map(i=><div key={i} className="h-24 animate-pulse rounded-xl border bg-muted/40"/>)}</div>:q.isError?<Card><CardContent className="p-8 text-center"><p className="font-medium">Leads could not be loaded.</p><p className="mt-2 text-sm text-muted-foreground">Check your staff access and try again.</p><Button variant="outline" className="mt-4" onClick={()=>q.refetch()}>Retry</Button></CardContent></Card>:!q.data?.length?<Card><CardContent className="p-10 text-center"><Users className="mx-auto h-8 w-8 text-muted-foreground"/><h2 className="mt-4 font-serif text-xl font-semibold">No captured leads yet</h2><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">Leads submitted through the IPM experience will show up here.</p></CardContent></Card>:<div className="space-y-3">{q.data.map(l=><Card key={l.id}><CardContent className="flex min-w-0 flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between sm:p-5"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-semibold">{l.name||"Unnamed lead"}</h2><Badge variant="secondary">{l.qualificationStatus||"new"}</Badge></div><div className="mt-2 flex min-w-0 flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground">{l.email&&<span className="inline-flex min-w-0 break-all items-center gap-1.5"><Mail className="h-3.5 w-3.5 shrink-0"/>{l.email}</span>}{l.phone&&<span className="inline-flex items-center gap-1.5"><Phone className="h-3.5 w-3.5"/>{l.phone}</span>}</div><p className="mt-2 break-words text-xs text-muted-foreground">{[l.locationPreference,l.budget,l.notes].filter(Boolean).join(" · ")||"No additional lead notes"}</p></div><Link href={`/staff/assistant?leadId=${encodeURIComponent(l.id)}`} className="inline-flex h-10 w-full shrink-0 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 sm:w-auto">Generate response <ArrowUpRight className="ml-2 h-4 w-4"/></Link></CardContent></Card>)}</div>}</div>;
}
